src/main/java/com/learn/epam/victorprudnikov/model/Coach.java
package com.learn.epam.victorprudnikov.model;

public class Coach extends Person{
	private String post;

	public Coach(int id, String name, String surname, int birthDay, int birthMonth, int birthYear, int games, String post) {
		super(id, name, surname, birthDay, birthMonth, birthYear, games);
		this.post = post;
	}

	public String getPost() {
		return post;
	}
	public void setPost(String post) {
		this.post = post;
	}
		

}

src/main/java/com/learn/epam/victorprudnikov/model/Person.java
package com.learn.epam.victorprudnikov.model;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;

public class Person {
	private int id;
	private String name;
	private String surname;
	private Calendar birthDate;
	private int games;
	
	public Person(int id, String name, String surname, int birthDay, int birthMonth, int birthYear, int games) {
		this.id = id;
		this.name = name;
		this.surname = surname;
		birthDate = new GregorianCalendar(birthYear, birthMonth, birthDay);
		this.games = games;
	}

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getSurname() {
		return surname;
	}
	public void setSurname(String surname) {
		this.surname = surname;
	}
	public String getBirthDate() {
		DateFormat df = new SimpleDateFormat("dd MMMM yyyy", Locale.ENGLISH);
		return df.format(birthDate.getTime());
	}
	public void setBirthDate(int birthDay, int birthMonth, int birthYear) {
		birthDate.set(Calendar.DAY_OF_MONTH, birthDay);
		birthDate.set(Calendar.MONTH, birthMonth);
		birthDate.set(Calendar.YEAR, birthYear);
	}
	public int getGames() {
		return games;
	}
	public void setGames(int games) {
		this.games = games;
	}
	public int getAge() {
		return LocalDate.now().minus(Period.of(this.getBirthYear(), this.getBirthMonth(), 
				this.getBirthDay())).getYear();
	}
	// Get date of birth view for the HTML-form.
	public String getBirthDateForForm() {
		DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
		return df.format(birthDate.getTime());
	}
	public int getBirthDay() {
		return birthDate.get(Calendar.DAY_OF_MONTH);
	}
	public int getBirthMonth() {
		return birthDate.get(Calendar.MONTH);
	}
	public int getBirthYear() {
		return birthDate.get(Calendar.YEAR);
	}
}

src/main/java/com/learn/epam/victorprudnikov/model/Position.java
package com.learn.epam.victorprudnikov.model;

//Field players position
public enum Position {
	DEFENDER ("Defender"),
	MIDFIELDER ("Midfielder"),
	STRIKER ("Striker");
	
	private String position;
	
	Position (String position) {
		this.position = position;
	}
	
	public String getPosition() {
		return position;
	}
}

src/main/java/com/learn/epam/victorprudnikov/controller/CoachesViewServlet.java
package com.learn.epam.victorprudnikov.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.learn.epam.victorprudnikov.database.CoachDB;
import com.learn.epam.victorprudnikov.model.Coach;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

//The servlet for viewing all coach records from the database.
public class CoachesViewServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private static final Logger logger = LogManager.getLogger();
	private CoachDB coachDB = new CoachDB();
	
	public CoachesViewServlet() {
		super();
	}
	
	//The constructor for the unit testing.
	CoachesViewServlet(CoachDB coachDB) {
		super();
		this.coachDB = coachDB;
	}
	
	protected void processRequest(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		try {
			List<Coach> coaches = coachDB.createList();
			if (coaches == null) {
				request.setAttribute("error", "Coach table is empty.");
				getServletContext().getRequestDispatcher("/somethingwrong.jsp").forward(request, response);
			}
			else {
				request.setAttribute("coaches", coaches);
				getServletContext().getRequestDispatcher("/coaches.jsp").forward(request, response);
			}
		}
		catch(Exception ex) {
			logger.error(ex.toString());
			request.setAttribute("error", ex.toString());
			getServletContext().getRequestDispatcher("/somethingwrong.jsp").forward(request, response);
		}
		
	}
	
	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		processRequest(request, response);
	}
	
	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		processRequest(request, response);
	}

}

src/main/java/com/learn/epam/victorprudnikov/controller/CreateServlet.java
package com.learn.epam.victorprudnikov.controller;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.learn.epam.victorprudnikov.database.CoachDB;
import com.learn.epam.victorprudnikov.database.GoalkeeperDB;
import com.learn.epam.victorprudnikov.database.PlayerDB;
import com.learn.epam.victorprudnikov.model.*;
import com.learn.epam.victorprudnikov.util.EmptyNameException;
import com.learn.epam.victorprudnikov.util.EmptyNumberException;
import com.learn.epam.victorprudnikov.util.NumberIsOccupiedException;
import com.learn.epam.victorprudnikov.util.NumberValidator;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

//The servlet for creating coach, goalkeeper or player record in the database.
public class CreateServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private static final Logger logger = LogManager.getLogger();
	private CoachDB coachDB = new CoachDB();
	private PlayerDB playerDB = new PlayerDB();
	private GoalkeeperDB goalkeeperDB = new GoalkeeperDB();
	private NumberValidator numberValidator = new NumberValidator();
	
	public CreateServlet() {
		super();
	}
	
	//The constructor for the unit testing.
	CreateServlet(CoachDB coachDB, PlayerDB playerDB, GoalkeeperDB goalkeeperDB, NumberValidator numberValidator) {
		super();
		this.coachDB = coachDB;
		this.playerDB = playerDB;
		this.goalkeeperDB = goalkeeperDB;
		this.numberValidator = numberValidator;
	}
	
	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		try {
			String createType = request.getParameter("createlist");
			if (createType == null) {
				logger.error("Error while creating new record - createType is null.");
				request.setAttribute("error", "createType is null");
				getServletContext().getRequestDispatcher("/somethingwrong.jsp").forward(request, response);
			} else {
				switch (createType) {
				case "coach": {
					getServletContext().getRequestDispatcher("/createcoach.jsp").forward(request, response);
					break;
				}
				case "goalkeeper": {
					getServletContext().getRequestDispatcher("/creategoalkeeper.jsp").forward(request, response);
					break;
				}
				case "fieldplayer": {
					getServletContext().getRequestDispatcher("/createfieldplayer.jsp").forward(request, response);
					break;
				}
				default: {
					logger.error("Error while creating new record - createType is unknown.");
					request.setAttribute("error", "createType is unknown");
					getServletContext().getRequestDispatcher("/somethingwrong.jsp").forward(request, response);
				}}
			}
		} catch (Exception ex) {
			logger.error(ex.toString());
			request.setAttribute("error", ex.toString());
			getServletContext().getRequestDispatcher("/somethingwrong.jsp").forward(request, response);
		}
	}

	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		try {
			String typeRequest = request.getParameter("typerequest");
			if (typeRequest == null) {
				logger.error("Error while creating new record - typeRequest is null.");
				request.setAttribute("error", "typeRequest is null");
				getServletContext().getRequestDispatcher("/somethingwrong.jsp").forward(request, response);
			} else {
				switch (typeRequest) {
				case "coach": {
					String coachName = request.getParameter("CoachName");
					String coachSurname = request.getParameter("CoachSurname");
					if (((coachName == null) || coachName.equals("")) && ((coachSurname == null) || coachSurname.equals(""))) {
						throw new EmptyNameException();
					}
					int coachBirthDay = Integer.parseInt((request.getParameter("CoachBirthDate")).substring(8));
					//Need to subtract 1 from month because in Calendar objects months starts from 0.
					int coachBirthMonth = Integer.parseInt((request.getParameter("CoachBirthDate")).substring(5, 7)) - 1;
					int coachBirthYear = Integer.parseInt((request.getParameter("CoachBirthDate")).substring(0, 4));
					int coachGames;
					if ((request.getParameter("CoachGames") == null) || (request.getParameter("CoachGames").equals(""))) {
						coachGames = 0;
					} else {
						coachGames = Integer.parseInt(request.getParameter("CoachGames"));
					}
					String coachPost = request.getParameter("CoachPost");
					Coach coach = new Coach(0, coachName, coachSurname, coachBirthDay, coachBirthMonth, coachBirthYear,
							coachGames, coachPost);
					String insertMessage = coachDB.insert(coach);
					if (insertMessage.equals("Success")) {
						logger.info("Created new coach record - " + coach.getName() + " " + coach.getSurname() + ".");
						response.sendRedirect(request.getContextPath() + "/coachesview");
					} else {
						logger.error(insertMessage);
						request.setAttribute("error", insertMessage);
						getServletContext().getRequestDispatcher("/somethingwrong.jsp").forward(request, response);
					}
					break;
				}
				case "goalkeeper": {
					int keeperGames, keeperGoals, keeperHeight, keeperWeight, goalsConceded, penaltySaved;
					if ((request.getParameter("KeeperNumber") == null) || (request.getParameter("KeeperNumber").equals(""))) {
						throw new EmptyNumberException();
					}
					int keeperNumber = Integer.parseInt(request.getParameter("KeeperNumber"));
					//Check if the number is occupied by other player.
					if (numberValidator.numberIsOccupied(keeperNumber)) {
						throw new NumberIsOccupiedException();
					}
					String keeperName = request.getParameter("KeeperName");
					String keeperSurname = request.getParameter("KeeperSurname");
					if (((keeperName == null) || keeperName.equals("")) && ((keeperSurname == null) || keeperSurname.equals(""))) {
						throw new EmptyNameException();
					}
					int keeperBirthDay = Integer.parseInt((request.getParameter("KeeperBirthDate")).substring(8));
					//Need to subtract 1 from month because in Calendar objects months starts from 0.
					int keeperBirthMonth = Integer.parseInt((request.getParameter("KeeperBirthDate")).substring(5, 7)) - 1;
					int keeperBirthYear = Integer.parseInt((request.getParameter("KeeperBirthDate")).substring(0, 4));
					if ((request.getParameter("KeeperGames") == null) || (request.getParameter("KeeperGames").equals(""))) {
						keeperGames = 0;
					} else {
						keeperGames = Integer.parseInt(request.getParameter("KeeperGames"));
					}
					if ((request.getParameter("KeeperGoals") == null) || (request.getParameter("KeeperGoals").equals(""))) {
						keeperGoals = 0;
					} else {
						keeperGoals = Integer.parseInt(request.getParameter("KeeperGoals"));
					}
					if ((request.getParameter("KeeperHeight") == null)
							|| (request.getParameter("KeeperHeight").equals(""))) {
						keeperHeight = 0;
					} else {
						keeperHeight = Integer.parseInt(request.getParameter("KeeperHeight"));
					}
					if ((request.getParameter("KeeperWeight") == null)
							|| (request.getParameter("KeeperWeight").equals(""))) {
						keeperWeight = 0;
					} else {
						keeperWeight = Integer.parseInt(request.getParameter("KeeperWeight"));
					}
					if ((request.getParameter("GoalsConceded") == null)
							|| (request.getParameter("GoalsConceded").equals(""))) {
						goalsConceded = 0;
					} else {
						goalsConceded = Integer.parseInt(request.getParameter("GoalsConceded"));
					}
					if ((request.getParameter("PenaltySaved") == null)
							|| (request.getParameter("PenaltySaved").equals(""))) {
						penaltySaved = 0;
					} else {
						penaltySaved = Integer.parseInt(request.getParameter("PenaltySaved"));
					}
					Goalkeeper keeper = new Goalkeeper(0, keeperNumber, keeperName, keeperSurname, keeperBirthDay,
							keeperBirthMonth, keeperBirthYear, keeperGames, keeperGoals, keeperHeight, keeperWeight,
							goalsConceded, penaltySaved, "Goalkeeper");
					String insertMessage = goalkeeperDB.insert(keeper);
					if (insertMessage.equals("Success")) {
						logger.info( "Created new goalkeeper record - " + keeper.getName() + " " + keeper.getSurname() + ".");
						response.sendRedirect(request.getContextPath() + "/teamview");
					} else {
						logger.error(insertMessage);
						request.setAttribute("error", insertMessage);
						getServletContext().getRequestDispatcher("/somethingwrong.jsp").forward(request, response);
					}
					break;
				}
				case "fieldplayer": {
					int playerGames, playerGoals, playerHeight, playerWeight;
					if ((request.getParameter("PlayerNumber") == null) || (request.getParameter("PlayerNumber").equals(""))) {
						throw new EmptyNumberException();
					}
					int playerNumber = Integer.parseInt(request.getParameter("PlayerNumber"));
					//Check if the number is occupied by other player.
					if (numberValidator.numberIsOccupied(playerNumber)) {
						throw new NumberIsOccupiedException();
					}
					String playerName = request.getParameter("PlayerName");
					String playerSurname = request.getParameter("PlayerSurname");
					if (((playerName == null) || playerName.equals("")) && ((playerSurname == null) || playerSurname.equals(""))) {
						throw new EmptyNameException();
					}
					int playerBirthDay = Integer.parseInt((request.getParameter("PlayerBirthDate")).substring(8));
					//Need to subtract 1 from month because in Calendar objects months starts from 0.
					int playerBirthMonth = Integer.parseInt((request.getParameter("PlayerBirthDate")).substring(5, 7)) - 1;
					int playerBirthYear = Integer.parseInt((request.getParameter("PlayerBirthDate")).substring(0, 4));
					if ((request.getParameter("PlayerGames") == null) || (request.getParameter("PlayerGames").equals(""))) {
						playerGames = 0;
					} else {
						playerGames = Integer.parseInt(request.getParameter("PlayerGames"));
					}

src/main/java/com/learn/epam/victorprudnikov/controller/TeamViewServlet.java
package com.learn.epam.victorprudnikov.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.learn.epam.victorprudnikov.database.PlayerDB;
import com.learn.epam.victorprudnikov.model.Player;
import com.learn.epam.victorprudnikov.database.GoalkeeperDB;
import com.learn.epam.victorprudnikov.model.Goalkeeper;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

//The servlet for viewing all goalkeeper and player records from the database.
public class TeamViewServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private static final Logger logger = LogManager.getLogger();
	private PlayerDB playerDB = new PlayerDB();
	private GoalkeeperDB goalkeeperDB = new GoalkeeperDB();
	
	public TeamViewServlet() {
		super();
	}
	
	//The constructor for the unit testing.
	TeamViewServlet(PlayerDB playerDB, GoalkeeperDB goalkeeperDB) {
		super();
		this.playerDB = playerDB;
		this.goalkeeperDB = goalkeeperDB;
	}
	
	protected void processRequest(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		try {
			List<Player> players = playerDB.createList();
			List<Goalkeeper> keepers = goalkeeperDB.createList();
			
			if (players == null) {
				request.setAttribute("error", "Field players table is empty.");
				getServletContext().getRequestDispatcher("/somethingwrong.jsp").forward(request, response);
			}
			else {
				if (keepers == null) {
					request.setAttribute("error", "Goalkeepers table is empty.");
					getServletContext().getRequestDispatcher("/somethingwrong.jsp").forward(request, response);
				} else {
					request.setAttribute("players", players);
					request.setAttribute("keepers", keepers);
					getServletContext().getRequestDispatcher("/team.jsp").forward(request, response);
				}
			}
		}
		catch(Exception ex) {
			logger.error(ex.toString());
			request.setAttribute("error", ex.toString());
			getServletContext().getRequestDispatcher("/somethingwrong.jsp").forward(request, response);
		}
		
	}
	
	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		processRequest(request, response);
	}
	
	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		processRequest(request, response);
	}

}

src/main/webapp/about.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>About - Renaissance FC</title>
<link rel="stylesheet" type="text/css" href="Styles/standard.css">
</head>
<body class="body">
	<jsp:include page="header.jsp" />
	<h3>
		This is a fan-site of imaginary footbal club - Renaissance FC. Imagine what if artists, sculptors, scientists and 
		philosophers of Renaissance age played football. Leonardo da Vinci as fantasista, Michelangelo as center forward, 
		wise Copernicus in charge. This site gives opportunity to store statistics of coaches and players.<br><br>
		But seriously, this is a training project as part of EPAM University Program (spring-summer 2020). 
		Humble author - Victor Prudnikov. 
	</h3>
</body>
</html>

src/main/webapp/coaches.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Coaches - Renaissance FC</title>
<link rel="stylesheet" type="text/css" href="Styles/standard.css">
</head>
<body class="body">
	<jsp:include page="header.jsp" />
	<h1>Coaches</h1>
	<table class="table1">
		<thead>
			<tr>
				<th><b>Name</b></th>
				<th><b>Surname</b></th>
				<th><b>Birth Date</b></th>
				<th><b>Age</b></th>
				<th><b>Games</b></th>
				<th><b>Post</b></th>
				<th colspan="2"><b>Operation</b></th>
			</tr>
		</thead>
		<tbody>
			<c:forEach items="${coaches}" var="coach">
				<tr>
					<td>${coach.name}</td>
					<td>${coach.surname}</td>
					<td>${coach.birthDate}</td>
					<td>${coach.age}</td>
					<td>${coach.games}</td>
					<td>${coach.post}</td>
					<td class="button"><form action="edit" method="GET">
							<input type="submit" value="  Edit  ">
							<input type="hidden" name="typerequest" value="coaches">
							<input type="hidden" name="id" value="${coach.id}">
						</form></td>
					<td class="button"><form action="delete" method="GET">
							<input type="submit" value="Delete">
							<input type="hidden" name="typerequest" value="coaches">
							<input type="hidden" name="id" value="${coach.id}">
						</form></td>
				</tr>
			</c:forEach>
		</tbody>
	</table>
	<br>
	<form class="center" action="/renaissancefc/create.jsp">
	<input type="submit" value="Create new record">
	</form>
</body>
</html>

src/main/webapp/deletecoach.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Delete Coach Record - Renaissance FC</title>
<link rel="stylesheet" type="text/css" href="Styles/standard.css">
</head>
<body class="body">
	<jsp:include page="header.jsp" />
	<h1>Are you sure you want to delete this record?</h1>
	<table class="table1">
		<thead>
			<tr>
				<th><b>Name</b></th>
				<th><b>Surname</b></th>
				<th><b>Birth Date</b></th>
				<th><b>Age</b></th>
				<th><b>Games</b></th>
				<th><b>Post</b></th>
			</tr>
		</thead>
		<tbody>
				<tr>
					<td>${coach.name}</td>
					<td>${coach.surname}</td>
					<td>${coach.birthDate}</td>
					<td>${coach.age}</td>
					<td>${coach.games}</td>
					<td>${coach.post}</td>
				</tr>
		</tbody>
	</table>
	<br><br>
	<div class="center">
	<form action="delete" method="POST">
		<input type="hidden" name="typerequest" value="coaches">
		<input type="hidden" name="id" value="${coach.id}">
  		<input type="submit" value="  OK  ">
  		<input type="submit" value ="Cancel" formaction="coachesview">
	</form>
	</div>
</body>
</html>

src/main/webapp/deletefieldplayer.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Delete Field Player Record - Renaissance FC</title>
<link rel="stylesheet" type="text/css" href="Styles/standard.css">
</head>
<body class="body">
	<jsp:include page="header.jsp" />
	<h1>Are you sure you want to delete this record?</h1>
	<table class="table1">
		<thead>
			<tr>
				<th><b>№</b></th>
				<th><b>Name</b></th>
				<th><b>Surname</b></th>
				<th><b>Birth Date</b></th>
				<th><b>Age</b></th>
				<th><b>Games</b></th>
				<th><b>Goals</b></th>
				<th><b>Height</b></th>
				<th><b>Weight</b></th>
				<th><b>Position</b></th>
			</tr>
		</thead>
		<tbody>
				<tr>
					<td>${player.number}</td>
					<td>${player.name}</td>
					<td>${player.surname}</td>
					<td>${player.birthDate}</td>
					<td>${player.age}</td>
					<td>${player.games}</td>
					<td>${player.goals}</td>
					<td>${player.height}</td>
					<td>${player.weight}</td>
					<td>${player.position}</td>
				</tr>
		</tbody>
	</table>
	<br><br>
	<div class="center">
	<form action="delete" method="POST">
		<input type="hidden" name="typerequest" value="players">
		<input type="hidden" name="id" value="${player.id}">
  		<input type="submit" value="  OK  ">
  		<input type="submit" value ="Cancel" formaction="teamview">
	</form>
	</div>
</body>
</html>

src/main/webapp/deletegoalkeeper.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Delete Goalkeeper Record - Renaissance FC</title>
<link rel="stylesheet" type="text/css" href="Styles/standard.css">
</head>
<body class="body">
	<jsp:include page="header.jsp" />
	<h1>Are you sure you want to delete this record?</h1>
	<table class="table1">
		<thead>
			<tr>
				<th><b>№</b></th>
				<th><b>Name</b></th>
				<th><b>Surname</b></th>
				<th><b>Birth Date</b></th>
				<th><b>Age</b></th>
				<th><b>Games</b></th>
				<th><b>Goals</b></th>
				<th><b>Height</b></th>
				<th><b>Weight</b></th>
				<th><b>Conceded</b></th>
				<th><b>Pen.Saved</b></th>
				<th><b>Position</b></th>
			</tr>
		</thead>
		<tbody>
				<tr>
					<td>${keeper.number}</td>
					<td>${keeper.name}</td>
					<td>${keeper.surname}</td>
					<td>${keeper.birthDate}</td>
					<td>${keeper.age}</td>
					<td>${keeper.games}</td>
					<td>${keeper.goals}</td>
					<td>${keeper.height}</td>
					<td>${keeper.weight}</td>
					<td>${keeper.goalsConceded}</td>
					<td>${keeper.penaltySaved}</td>
					<td>${keeper.position}</td>
				</tr>
		</tbody>
	</table>
	<br><br>
	<div class="center">
	<form action="delete" method="POST">
		<input type="hidden" name="typerequest" value="keepers">
		<input type="hidden" name="id" value="${keeper.id}">
  		<input type="submit" value="  OK  ">
  		<input type="submit" value ="Cancel" formaction="teamview">
	</form>
	</div>
</body>
</html>

src/main/webapp/editcoach.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Edit Coach Record - Renaissance FC</title>
<link rel="stylesheet" type="text/css" href="Styles/standard.css">
</head>
<body class="body">
	<jsp:include page="header.jsp" />
	<h1>Edit Coach Record</h1>
	<form class="divform" action="edit" method="POST">
		<input type="hidden" name="typerequest" value="coaches">
		<input type="hidden" name="id" value="${coach.id}">
		<label for="CoachName">Name:</label><br>
  		<input type="text" id="CoachName" name="CoachName" value="${coach.name}"><br>
  		<br>
  		<label for="CoachSurname">Surname:</label><br>
  		<input type="text" id="CoachSurname" name="CoachSurname" value="${coach.surname}"><br>
  		<br>
  		<label for="CoachBirthDate">Birth Date:</label><br>
  		<input type="date" id="CoachBirthDate" name="CoachBirthDate" value="${coach.birthDateForForm}"><br>
  		<br>
  		<label for="CoachGames">Games:</label><br>
  		<input type="number" id="CoachGames" name="CoachGames" min="0" value="${coach.games}"><br>
  		<br>
  		<label for="CoachPost">Post:</label><br>
  		<input list="CoachPosts" name="CoachPost" value="${coach.post}"><br>
  		<br>
  		<datalist id="CoachPosts">
  			<c:forEach items="${postlist}" var="post">
  				<option value="${post.post}">
  			</c:forEach>
  		</datalist><br>
  		<input type="submit" value="  OK  ">
  		<input type="submit" value ="Cancel" formaction="coachesview">
	</form>
</body>
</html>

src/main/webapp/header.jsp
<div class="divheader">
<nav class="navbar">
	<ul>
		<li><a href="/renaissancefc/index.jsp">Home</a></li>
		<li><a href="/renaissancefc/coachesview">Coaches</a></li>
		<li><a href="/renaissancefc/teamview">Team</a></li>
		<li><a href="/renaissancefc/fans.jsp">Fans</a></li>
		<li><a href="/renaissancefc/about.jsp">About</a></li>
	</ul>
</nav>
</div>